### ISSUE TITLE
Inconsistent CSS property name color

### ISSUE THREAD

**Issue by passerbyxp** [NLKNguyen/papercolor-theme#170]
This is what I got from papercolor (left) vs [vim-unicon](https://github.com/andbar-ru/vim-unicon) (right, which claims to have no language specific syntax):

<img src="https://i.imgur.com/KJnQm4e.png" alt="versus" />

As you can see, not all property names are using the same color, and `transparent` is highlighted like a property name, not a value.  
(`12.5em` got highlighted into two different tokens is a nice feature, though.)

Is it possible to make papercolor work better on CSS?

[vim-css3-syntax](https://github.com/hail2u/vim-css3-syntax) and [vim-css-color](https://github.com/ap/vim-css-color) are used in the above screenshot, and also this file segment:

```css
body
{
	font-size:16px;
	font-family:"微软雅黑","微軟雅黑","Microsoft YaHei","Source Han Sans","Noto Sans","WenQuanYi Micro Hei","文泉驿微米黑",sans-serif;
	padding:0.5em;
	background-color:#FAFAFA;/* grey 50 */
}
body.toolbar
{
	padding-left:2.5em;
}
body.toolbar:not(.manual-navigator)
{
	padding-left:12.5em;
}
.bg-trans
{
	background-color:transparent;
}
.nowrap
{
	white-space:nowrap;
}
.pre
{
	white-space:pre;
}
.pre-wrap
{
	white-space:pre-wrap;
}
.text-ellipsis
{
	overflow:hidden;
	text-overflow:ellipsis;
}
.word-break
{
	word-wrap:break-word;
	word-break:break-all;
}
.over-hold
{
	overflow:auto;
}
.over-hide
{
	overflow:hidden;
}
.over-show
{
	overflow:visible;
}
.bg-primary
{
	background-color:#2196F3;
}
```
