### ISSUE TITLE
Add CSS highlighting

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#49]
I look for nice CSS syntax online, seems like none sustified my expectations.

**Comment by NLKNguyen** [comment]
The theme currently has partial support for CSS. I need to work on that. Can you provide some CSS snippets that show the incompleteness of the theme support, so I can work on. The CSS syntax groups from the built in syntax file are unnecessarily many, and I didn't encounter most of them.

**Comment by pickfire** [comment]
My site's css:
```css
html {
	height: 100%;
}

body {
	margin: 0; padding: 0;
	position: relative;
	min-height: 100%;
	font-family: sans-serif;
	color: #444; background-color: #F5F5F5;
}

header {
	padding: 5px 15px;
	border-top: 2px solid #444;
	text-shadow: 2px 1px #ccc;
	font-size: 250%;
	color: #3a3a3a; background-color: #e4e4e4;
}

footer {
	position: absolute;
	bottom: 0; left: 0; right: 0;
	padding: 1ex 1em 1em;
	font-size: 85%;
	border-top: 1px solid #ccc;
	color: #666; background-color: #eee;
}

header,footer {display:block;}

#fire {
	display: inline-block;
	width: 40px; height: 40px; margin: 0 5px -2px 0;
	background: url(/img/fire.gif);
}
#fire:hover	{background-position:-40px 0;}
#fire:active	{background-position:-80px 0;}

#main {
	overflow: hidden;
	margin: 1em 0 0 202px;
	padding: 0 4ex 6ex;

}

#menu {
	overflow: hidden;
	background-color: #e4e4e4;
	font-size: 1.6em;
}

#menu a {
	padding: 1ex;
	color: #444;
}

#menu #here, #menu a:hover {
	background-color: #F5F5F5;
}

a { text-decoration: none; color: #4271ae; }
#nav a:hover, li a:hover, p a:hover { background-color: #e4e4e4; } /* TODO: Shorten this */

#main img { max-width: 100%; max-height: 100% }

p code, pre {
	color: #555; background-color: #EEE;
	border: 1px solid;
}
p code {padding: 0 3px;}
pre {padding: 9px 1em; border-radius: 5px;}

blockquote {
	color: #616161;
	overflow: auto;
	margin: 0; padding: 0 1em;
	border-left: 5px solid #e4e4e4;
}

.left	{margin:0;padding:0;float:left;}
.right	{margin:0;padding:0;float:right;}
```
And add for this support too:
```css
body {
    min-height: calc(100% - 1px);
}
```
